### ISSUE TITLE
.net fails to build

### ISSUE THREAD

**Issue by uberbigun** [blacklanternsecurity/enter_the_matrix#1]
Clean install of LTS18.04.5. Followed the tutorial. During docker build, I recieve the following error:

root@TheMatrix:/var/matrix/app/enter_the_matrix# docker-compose up -d
Building etm
Step 1/9 : FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
 ---> 5fe503d51830
Step 2/9 : WORKDIR /var/matrix/app/enter_the_matrix
 ---> Using cache
 ---> 4744c3880f13
Step 3/9 : COPY *.csproj .
 ---> Using cache
 ---> d99e6bda84c4
Step 4/9 : RUN dotnet restore
 ---> Using cache
 ---> c8a073ad698c
Step 5/9 : COPY . .
 ---> Using cache
 ---> cccfc72cfbd8
Step 6/9 : RUN dotnet publish --configuration Release
 ---> Running in 1327cb573394
Microsoft (R) Build Engine version 16.7.0+7fb82e5b2 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
/usr/share/dotnet/sdk/3.1.403/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(241,5): error NETSDK1064: Package Microsoft.CodeAnalysis.Analyzers, version 2.9.4 was not found. It might have been deleted since NuGet restore. Otherwise, NuGet restore might have only partially completed, which might have been due to maximum path length restrictions. [/var/matrix/app/enter_the_matrix/Enter_The_Matrix.csproj]
ERROR: Service 'etm' failed to build: The command '/bin/sh -c dotnet publish --configuration Release' returned a non-zero code: 1

**Comment by debifrank** [comment]
Sorry for the delayed response. I investigated the issue and it seems a few extra steps are needed before it can be deployed with docker-compose. I will copy the steps here and make the necessary changes to the README. Thank you for pointing this out!

Before deploying with `docker-compose up -d` do the following on a fresh Ubuntu 18.04 install:

- `wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb`
- `sudo dpkg -i packages-microsoft-prod.deb`
- ```sudo apt-get update; \
  sudo apt-get install -y apt-transport-https && \
  sudo apt-get update && \
  sudo apt-get install -y dotnet-sdk-5.0```
- `cd /var/matrix/app/enter_the_matrix`
- `dotnet publish --configuration Release`

This will publish the application and create the necessary files docker-compose needs. From here, deploy with `docker-compose up -d`
